// Auto-generated from OpenAPI spec. Do not edit manually. Regenerate: scripts/generate-contracts.sh

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Check */
        get: operations["readiness_check_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Elections */
        get: operations["list_elections_api_v1_elections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elections/{election_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Election */
        get: operations["get_election_api_v1_elections__election_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elections/{election_id}/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Election Races */
        get: operations["list_election_races_api_v1_elections__election_id__races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts/{district_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get District */
        get: operations["get_district_api_v1_districts__district_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/districts/{district_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Child Districts */
        get: operations["list_child_districts_api_v1_districts__district_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_api_v1_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_v1_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidacies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidacies */
        get: operations["list_candidacies_api_v1_candidacies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidacies/{candidacy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidacy */
        get: operations["get_candidacy_api_v1_candidacies__candidacy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidacies/{candidacy_id}/promises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidacy Promises */
        get: operations["list_candidacy_promises_api_v1_candidacies__candidacy_id__promises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidacies/{candidacy_id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidacy Claims */
        get: operations["list_candidacy_claims_api_v1_candidacies__candidacy_id__claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ballots/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Ballot */
        post: operations["resolve_ballot_api_v1_ballots_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issues */
        get: operations["list_issues_api_v1_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Issue */
        get: operations["get_issue_api_v1_issues__issue_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Candidacies */
        post: operations["compare_candidacies_api_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/elections/{election_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Election Live Updates */
        get: operations["stream_election_live_updates_api_v1_elections__election_id__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/election-windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Election Windows */
        get: operations["list_election_windows_api_v1_compliance_election_windows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/election-windows/{election_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Election Window Status */
        get: operations["get_election_window_status_api_v1_compliance_election_windows__election_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Audit Log */
        post: operations["create_audit_log_api_v1_compliance_audit_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publish/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Snapshot */
        post: operations["publish_snapshot_api_v1_admin_publish_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogCreate */
        AuditLogCreate: {
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Reason Code */
            reason_code?: string | null;
            /** Old Value */
            old_value?: {
                [key: string]: unknown;
            } | null;
            /** New Value */
            new_value?: {
                [key: string]: unknown;
            } | null;
            /** Legal Basis */
            legal_basis?: string | null;
        };
        /** BallotRaceResult */
        BallotRaceResult: {
            race: components["schemas"]["RaceRead"];
            /** Candidacies */
            candidacies: components["schemas"]["CandidacySummary"][];
        };
        /** BallotResolveRequest */
        BallotResolveRequest: {
            /** Address Text */
            address_text: string;
        };
        /** BallotResolveResponse */
        BallotResolveResponse: {
            district: components["schemas"]["DistrictRead"];
            /** Races */
            races: components["schemas"]["BallotRaceResult"][];
        };
        /** BillSponsorshipSummary */
        BillSponsorshipSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Bill Name */
            bill_name: string;
            /** Role */
            role: string;
            status: components["schemas"]["BillStatus"];
        };
        /**
         * BillStatus
         * @enum {string}
         */
        BillStatus: "proposed" | "committee_review" | "plenary" | "passed" | "rejected" | "withdrawn";
        /** CandidacyDetail */
        CandidacyDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            /** Party Id */
            party_id: string | null;
            status: components["schemas"]["CandidacyStatus"];
            /** Registered At */
            registered_at: string | null;
            /** Candidate Number */
            candidate_number: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            person: components["schemas"]["PersonSummary"];
            party: components["schemas"]["PartySummary"] | null;
            /** Promises */
            promises: components["schemas"]["PromiseRead"][];
            /** Claims */
            claims: components["schemas"]["ClaimRead"][];
        };
        /**
         * CandidacyStatus
         * @enum {string}
         */
        CandidacyStatus: "registered" | "withdrawn" | "disqualified" | "elected" | "defeated";
        /** CandidacySummary */
        CandidacySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            status: components["schemas"]["CandidacyStatus"];
            /** Candidate Number */
            candidate_number: number | null;
        };
        /** ClaimRead */
        ClaimRead: {
            /**
             * Candidacy Id
             * Format: uuid
             */
            candidacy_id: string;
            /**
             * Source Doc Id
             * Format: uuid
             */
            source_doc_id: string;
            claim_type: components["schemas"]["ClaimType"];
            /**
             * Is Legally Restricted
             * @default false
             */
            is_legally_restricted: boolean;
            /** Content */
            content: string;
            /** Excerpt */
            excerpt?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "official_fact" | "sourced_claim" | "opinion" | "disputed" | "ai_summary";
        /** CommitteeAssignmentSummary */
        CommitteeAssignmentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Committee Name */
            committee_name: string;
            /** Role */
            role: string | null;
            /** Start Date */
            start_date: string | null;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Candidacy Ids */
            candidacy_ids: string[];
        };
        /** ComparedPromise */
        ComparedPromise: {
            /**
             * Candidacy Id
             * Format: uuid
             */
            candidacy_id: string;
            /** Person Name */
            person_name: string;
            /** Party Name */
            party_name: string | null;
            /** Promises */
            promises: components["schemas"]["PromiseSummary"][];
        };
        /** ComparisonByIssue */
        ComparisonByIssue: {
            /** Issue Id */
            issue_id: string | null;
            /** Issue Name */
            issue_name: string | null;
            /** Candidates */
            candidates: components["schemas"]["ComparedPromise"][];
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Candidacy Ids */
            candidacy_ids: string[];
            /** By Issue */
            by_issue: components["schemas"]["ComparisonByIssue"][];
        };
        /** ComplianceAuditLogRead */
        ComplianceAuditLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Reason Code */
            reason_code: string | null;
            /** Old Value */
            old_value: {
                [key: string]: unknown;
            } | null;
            /** New Value */
            new_value: {
                [key: string]: unknown;
            } | null;
            /** Legal Basis */
            legal_basis: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ComplianceElectionWindowRead */
        ComplianceElectionWindowRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Election Id
             * Format: uuid
             */
            election_id: string;
            /** Content Type */
            content_type: string;
            /**
             * Blackout Start
             * Format: date-time
             */
            blackout_start: string;
            /**
             * Blackout End
             * Format: date-time
             */
            blackout_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DistrictRead */
        DistrictRead: {
            /** Name Ko */
            name_ko: string;
            /** Name En */
            name_en?: string | null;
            /** Level */
            level: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Code */
            code: string;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DistrictSummary */
        DistrictSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Ko */
            name_ko: string;
            /** Level */
            level: string;
            /** Code */
            code: string;
        };
        /** ElectionDetail */
        ElectionDetail: {
            /** Name */
            name: string;
            election_type: components["schemas"]["ElectionType"];
            /**
             * Election Date
             * Format: date
             */
            election_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Races */
            races: components["schemas"]["RaceRead"][];
        };
        /** ElectionSummary */
        ElectionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Election Date
             * Format: date
             */
            election_date: string;
        };
        /**
         * ElectionType
         * @enum {string}
         */
        ElectionType: "local_general" | "local_byelection";
        /** ElectionWindowStatusRead */
        ElectionWindowStatusRead: {
            /**
             * Election Id
             * Format: uuid
             */
            election_id: string;
            /** Content Type */
            content_type: string;
            /** Blocked */
            blocked: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            active_window?: components["schemas"]["ComplianceElectionWindowRead"] | null;
        };
        /** EntityCatalogEntry */
        EntityCatalogEntry: {
            /** Table */
            table: string;
            /** Description */
            description: string;
            /** Priority */
            priority: string;
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "male" | "female" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IssueDetail */
        IssueDetail: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Related Promises */
            related_promises: components["schemas"]["IssuePromiseSummary"][];
        };
        /** IssuePromiseSummary */
        IssuePromiseSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Candidacy Id
             * Format: uuid
             */
            candidacy_id: string;
            /** Title */
            title: string;
            /** Sort Order */
            sort_order: number;
            candidacy: components["schemas"]["CandidacySummary"];
        };
        /** IssueSummary */
        IssueSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id: string | null;
        };
        /** IssueTreeNode */
        IssueTreeNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id: string | null;
            /** Children */
            children: components["schemas"]["IssueTreeNode"][];
        };
        /** PartySummary */
        PartySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Ko */
            name_ko: string;
            /** Abbreviation */
            abbreviation: string | null;
            /** Color Hex */
            color_hex: string | null;
        };
        /** PersonCandidacySummary */
        PersonCandidacySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /**
             * Race Id
             * Format: uuid
             */
            race_id: string;
            status: components["schemas"]["CandidacyStatus"];
            /** Candidate Number */
            candidate_number: number | null;
        };
        /** PersonDetail */
        PersonDetail: {
            /** Name Ko */
            name_ko: string;
            /** Name En */
            name_en?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** External Ids */
            external_ids?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Candidacies */
            candidacies: components["schemas"]["PersonCandidacySummary"][];
            /** Committee Assignments */
            committee_assignments: components["schemas"]["CommitteeAssignmentSummary"][];
            /** Bill Sponsorships */
            bill_sponsorships: components["schemas"]["BillSponsorshipSummary"][];
        };
        /** PersonSummary */
        PersonSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Ko */
            name_ko: string;
            /** Name En */
            name_en: string | null;
            /** Photo Url */
            photo_url: string | null;
        };
        /**
         * PositionType
         * @enum {string}
         */
        PositionType: "mayor" | "governor" | "council_member" | "superintendent" | "proportional_council";
        /** PromiseRead */
        PromiseRead: {
            /**
             * Candidacy Id
             * Format: uuid
             */
            candidacy_id: string;
            /** Title */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Category */
            category?: string | null;
            /** Issue Id */
            issue_id?: string | null;
            /** Source Doc Id */
            source_doc_id?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PromiseSummary */
        PromiseSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Candidacy Id
             * Format: uuid
             */
            candidacy_id: string;
            /** Title */
            title: string;
            /** Sort Order */
            sort_order: number;
        };
        /** RaceRead */
        RaceRead: {
            /**
             * Election Id
             * Format: uuid
             */
            election_id: string;
            /**
             * District Id
             * Format: uuid
             */
            district_id: string;
            position_type: components["schemas"]["PositionType"];
            /**
             * Seat Count
             * @default 1
             */
            seat_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Persons */
            persons: components["schemas"]["PersonSummary"][];
            /** Issues */
            issues: components["schemas"]["IssueSummary"][];
            /** Parties */
            parties: components["schemas"]["PartySummary"][];
        };
        /** SnapshotPublishRequest */
        SnapshotPublishRequest: {
            /** Version */
            version: string;
            /** Schema Version */
            schema_version: string;
            /** Generated At */
            generated_at: string;
            /** Entity Catalog */
            entity_catalog: components["schemas"]["EntityCatalogEntry"][];
            /** Entity Count */
            entity_count: number;
            /** Publish Targets */
            publish_targets: string[];
        };
        /** SnapshotPublishResponse */
        SnapshotPublishResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * SourceDocKind
         * @enum {string}
         */
        SourceDocKind: "official_gazette" | "news_article" | "pdf" | "web_page" | "api_response";
        /** SourceDocRead */
        SourceDocRead: {
            kind: components["schemas"]["SourceDocKind"];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Is Poll Result
             * @default false
             */
            is_poll_result: boolean;
            /** Content Hash */
            content_hash?: string | null;
            /** Raw S3 Key */
            raw_s3_key?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_check_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_elections_api_v1_elections_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_election_api_v1_elections__election_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_election_races_api_v1_elections__election_id__races_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_district_api_v1_districts__district_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                district_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_child_districts_api_v1_districts__district_id__children_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                district_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_api_v1_persons_get: {
        parameters: {
            query?: {
                name?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_v1_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidacies_api_v1_candidacies_get: {
        parameters: {
            query?: {
                election_id?: string | null;
                district_id?: string | null;
                race_id?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidacySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidacy_api_v1_candidacies__candidacy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidacy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidacyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidacy_promises_api_v1_candidacies__candidacy_id__promises_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidacy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromiseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidacy_claims_api_v1_candidacies__candidacy_id__claims_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidacy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_ballot_api_v1_ballots_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BallotResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallotResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_issues_api_v1_issues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueTreeNode"][];
                };
            };
        };
    };
    get_issue_api_v1_issues__issue_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                type?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_candidacies_api_v1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_election_live_updates_api_v1_elections__election_id__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_election_windows_api_v1_compliance_election_windows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceElectionWindowRead"][];
                };
            };
        };
    };
    get_election_window_status_api_v1_compliance_election_windows__election_id__status_get: {
        parameters: {
            query: {
                content_type: string;
            };
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionWindowStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audit_log_api_v1_compliance_audit_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceAuditLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_snapshot_api_v1_admin_publish_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
